# Generated by Django 5.1.6 on 2025-05-21 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_co', '0002_predictionresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predictionresult',
            options={'ordering': ['-created_at'], 'verbose_name': 'Past order prediction', 'verbose_name_plural': 'Past order predictions'},
        ),
        migrations.AlterField(
            model_name='partyorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
